### ISSUE TITLE
installation problem, what is wrong ? 

### ISSUE THREAD

**Issue by KatjaM2020** [uw-ipd/RoseTTAFold2NA#33]
ld2NA/RoseTTAFold2NA/example$ ../run_RF2NA.sh t000_ protein.fa R:RNA.fa
Running RoseTTAFold2NA to predict structures
Running on CPU
           plddt    best
/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/amp/autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/predict.py", line 225, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, "%s_%02d"%(out_prefix, i_trial))
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/predict.py", line 269, in _run_model
    logit_s, logit_aa_s, logit_pae, init_crds, alpha_prev, _, pred_lddt_binned, msa_prev, pair_prev, state_prev = self.model(
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/RoseTTAFoldModel.py", line 96, in forward
    msa, pair, xyz, alpha_s, xyzallatom, state = self.simulator(
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/Track_module.py", line 430, in forward
    msa_full, pair, xyz, state, alpha = self.extra_block[i_m](msa_full, pair,
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/Track_module.py", line 356, in forward
    xyz, state, alpha = self.str2str(msa.float(), pair.float(), xyz.detach().float(), state.float(), idx, top_k=top_k)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/Track_module.py", line 223, in forward
    shift = self.se3(G, node.reshape(B*L, -1, 1), l1_feats, edge_feats)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/katja/BIGDATA/RoseTTAFold2NA/RoseTTAFold2NA/network/SE3_network.py", line 83, in forward
    return self.se3(G, node_features, edge_features) #, clamp_d=clamp_d)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/se3_transformer-1.0.0-py3.8.egg/se3_transformer/model/transformer.py", line 163, in forward
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/se3_transformer-1.0.0-py3.8.egg/se3_transformer/model/basis.py", line 166, in get_basis
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/cuda/nvtx.py", line 86, in range
    range_push(msg.format(*args, **kwargs))
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/cuda/nvtx.py", line 28, in range_push
    return _nvtx.rangePushA(msg)
  File "/home/katja/anaconda3/envs/RF2NA/lib/python3.8/site-packages/torch/cuda/nvtx.py", line 9, in _fail
    raise RuntimeError("NVTX functions not installed. Are you sure you have a CUDA build?")
RuntimeError: NVTX functions not installed. Are you sure you have a CUDA build?

**Comment by rgogal** [comment]
I am having the same issue despite installing it a few times. Were you able to find a resolution?

**Comment by KatjaM2020** [comment]
I know more people who has the same issue.
The interesting moment that the earlier downloaded program was installed without this issue.
This appeared after the latest updates.

From: rgogal ***@***.***>
Reply to: uw-ipd/RoseTTAFold2NA ***@***.***>
Date: Tuesday, 6 December 2022 at 20:31
To: uw-ipd/RoseTTAFold2NA ***@***.***>
Cc: Ekaterina Morgunova ***@***.***>, Author ***@***.***>
Subject: Re: [uw-ipd/RoseTTAFold2NA] installation problem, what is wrong ? (Issue #33)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I am having the same issue despite installing it a few times. Were you able to find a resolution?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fuw-ipd%2FRoseTTAFold2NA%2Fissues%2F33%23issuecomment-1339897831&data=05%7C01%7Cekaterina.morgunova%40ki.se%7C1c7677ee500a42df47d508dad7c068ae%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638059518641205638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ITeOQcvp%2BUfS%2BDaEcy1MXDP55MQb%2Ft%2FU%2Bkm4sWLv%2FYc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOJ2NRBYCFK6AHOKIY7EZE3WL6H7HANCNFSM6AAAAAASUCXAFM&data=05%7C01%7Cekaterina.morgunova%40ki.se%7C1c7677ee500a42df47d508dad7c068ae%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638059518641205638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0PYbtGPJpjc52M2gd07NA4bF1bmIK8VopbsPbivMofc%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by AlvinLou** [comment]
Same here, I was wondering if this is because of the CUDA version? I am using CUDA11.5.119 on Ubuntu 22.04.1 LTS.

**Comment by KatjaM2020** [comment]
Probably not. We started with CUDA 10 and Ubuntu 19.01. Then upgraded everything and got the same error.

From: Alvin LOU ***@***.***>
Reply to: uw-ipd/RoseTTAFold2NA ***@***.***>
Date: Thursday, 8 December 2022 at 07:04
To: uw-ipd/RoseTTAFold2NA ***@***.***>
Cc: Ekaterina Morgunova ***@***.***>, Author ***@***.***>
Subject: Re: [uw-ipd/RoseTTAFold2NA] installation problem, what is wrong ? (Issue #33)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Same here, I was wondering if this is because of the CUDA version? I am using CUDA11.5.119 on Ubuntu 22.04.1 LTS.

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fuw-ipd%2FRoseTTAFold2NA%2Fissues%2F33%23issuecomment-1342106426&data=05%7C01%7Cekaterina.morgunova%40ki.se%7C31dbb18d6ab947050e3e08dad8e21f22%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638060762941320312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O%2BjvRCnVr2u4szz36ynNozIGcYcc2jXuQ6eYmzFKmak%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOJ2NRHORKW3DSZCRADUOATWMF3AFANCNFSM6AAAAAASUCXAFM&data=05%7C01%7Cekaterina.morgunova%40ki.se%7C31dbb18d6ab947050e3e08dad8e21f22%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638060762941320312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NcP5%2FhNsMwYBQOUXk94D0zjSj6UBHD4e8NOojgQZaz8%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by rgogal** [comment]
I got mine running. My CUDA version was 11.3 and it is not compatible with pytorch 1.13 which is installed with the environment file. I have to downgrade my pytorch version in my environment. Here is the command I used. 
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge

**Comment by sa-minami** [comment]
I had the same error as KatjaM2020 and the solution by rgogal worked for me as well.

**Comment by AlvinLou** [comment]
> I had the same error as KatjaM2020 and the solution by rgogal worked for me as well.

I am using the CUDA 11.6 and NVIDIA-SMI 470.161.03, but the problem is still there.

**Comment by sa-minami** [comment]
> > I got mine running. My CUDA version was 11.3 and it is not compatible with pytorch 1.13 which is installed with the environment file. Pytorch 1.13 is only compatible with CUDA 11.6 and above. I had to downgrade my pytorch version in my environment. Here is the command I used. conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge
> 
> Do you have any specific reasons for using the CUDA 11.3 version? I am on 11.6 but the problem still can't be solved.

I started with 11.6, but that did not work for me. This was with Pytorch 1.13. I then downgraded both and it worked for me.

**Comment by i-l-sokolov** [comment]
> I got mine running. My CUDA version was 11.3 and it is not compatible with pytorch 1.13 which is installed with the environment file. Pytorch 1.13 is only compatible with CUDA 11.6 and above. I had to downgrade my pytorch version in my environment. Here is the command I used. conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge

I installed all requirements from the file in repository, had the same problem, tried this downgrading of libraries versions, but problem remains. If anyone have ideas what could be wrong, I would be very grateful. Thank you in advance

**Comment by dpretorius** [comment]
I have the same error when trying to run my script as @KatjaM2020

I am running it on:
**Ubantu 20.4
Nvidia Driver version 470.161.03
CUDA version 11.4**

Any developments on this?

**Comment by aylindmm** [comment]
What worked for me was uninstalling PyTorch and installing it again cording to my OS and CUDA version. 

[https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)

**Comment by SuhasSrinivasan** [comment]
Hello everyone, please see #105 for potential solution.
